[package]
name = "busybees"
version = "0.1.0"
authors = ["kevlarr"]
edition = "2018"

[dependencies]
chrono = "0.4"
futures = "0.3"
horrorshow = "0.8"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "0.2", features = ["macros"] }
warp = "0.2"

pretty_env_logger = "0.3"
