[package]
name = "busybees"
version = "0.1.0"
authors = ["kevlarr"]
edition = "2018"

[dependencies]
chrono = "0.4"
horrorshow = "0.8.1"
tokio = { version = "0.2", features = ["macros"] }
warp = "0.2"
